### ISSUE TITLE
Не обрабатываются запросы на порт ноды

### ISSUE THREAD

**Issue by BANOnotIT** [latur/dH#1]
И так, есть несколько вопросов, первый из них: зачем использовать php и ноду одновременно? Это что вообще такое?
Второй: почему игра не работает? Такое чувство, что просто сервер не работает, потому что порт 8967 не отвечает вообще ни на что.

Просьба перезапустить его, хотелось бы поиграть всё-таки)
И просьба установить утилиту forever, чтобы она автоматом поднимала сервер. Хотя и супервизора бы хватило, но forever будет тут лучше.

**Comment by latur** [comment]
> зачем использовать php и ноду одновременно? Это что вообще такое?

— Комментарий попахивает каким-то снобизмом ;) Согласен, но мне лень. Если ты всё перепишешь на ноду, будет хорошо. Можешь заодно выпилить авторизацию по вк, ибо атавизм. 
— Игра не работала, я переезжал. 
— Да, у меня всё висит на forever'е, этого просто нет в репозитории, кажется
